name: mobile-phone-network-analysis
channels:
  - conda-forge
dependencies:
  - geojson
  - geopandas
  - jupyterlab
  - nbclient
  - nbformat
  - numpy
  - pip
  - pyspark
  - python=3.9
  - scipy
  - pip:
    - pyproj
    - nbclick
