name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  linux-test:
    name: Testing on Linux
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache even if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('environment.yml') }}
    - name: Create mobile-phone-network-analysis conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: mobile-phone-network-analysis
        environment-file: environment.yml
        use-only-tar-bz2: true

    - name: Install development dependencies
      run: |
        python -m pip install -r requirements-dev.txt

    - name: Generate synthetic test data
      run: |
        nbclick ./notebooks/syntheticdata.ipynb --data_directory ./data

    - name: Run Python tests including notebooks
      run: |
        python -m pytest --nbval
